[InputMethod]
Name=Xiaohe
Name[zh_CN]=小鹤双拼
Icon=fcitx-pinyin
Label=鹤
LangCode=zh_CN
Addon=table
Configurable=True

[Table]
File=xhup.main.dict
AutoSelect=True
AutoSelectLength=-1
NoMatchAutoSelectLength=-1
NoSortInputLength=2
Hint=True
OrderPolicy=Freq
UseFullWidth=True
